# How to Donwload Cognite Database?

In [1]:
%config InlineBackend.figure_format = 'retina'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [5]:
import matplotlib.pyplot as plt
import atlas_mpl_style as ampl
import os, warnings
import matplotlib

from loguru import logger
from itm.clients import Cognite
from datetime import datetime

ampl.use_atlas_style()
plt.rcParams['font.family'] = 'DeJavu Sans'
plt.rcParams['font.serif'] = ['Times New Roman']
warnings.filterwarnings("ignore")
matplotlib.use('Agg')

## How to connect?

In [6]:
CLIENT_SECRET = "olz8Q~.m0ldyXULnMnry_NiWhb~2FDmgWYzeBcKZ" # this came from CDF token generation page
TENANT_ID     = "48d5043c-cf70-4c49-881c-c638f5796997" # this is the dataset project id
client        = Cognite("compressor", client_secret=CLIENT_SECRET, tenant_id=TENANT_ID)

2026-03-28 20:15:50.096 | INFO     | itm.clients.cognite:__init__:72 - publicdata

In [9]:
start_time = datetime(2019, 9, 1) # Tempo disponível no dataset (6 meses)
end_time = datetime(2020, 3, 1)
df, info = client.get_dataframe( '23-KA-9101', start_time, end_time )

2026-03-28 20:18:59.217 | INFO     | itm.clients.cognite:get_dataframe:178 - Searching data from 2019-09-01 00:00:00 to 2020-03-01 00:00:00 for asset '23-KA-9101'

{'VAL_23-KA-9101_APE:VALUE': 'PH (CBM) 1st Stage ActCompr Poly Eff',
 'VAL_23-KA-9101_APH:VALUE': 'PH (CBM) 1st Stg ActCompr Poly Head',
 'VAL_23-KA-9101_APR:VALUE': 'PH (CBM) 1st Stage ActPress Ratio',
 'VAL_23-KA-9101_ASP:VALUE': 'PH (CBM) 1st Stage ActShaft Power',
 'VAL_23-KA-9101_EPE:VALUE': 'PH (CBM) 1st Stage ExpCompr Poly Eff',
 'VAL_23-KA-9101_EPH:VALUE': 'PH (CBM) 1st Stg ExpCompr Poly Head',
 'VAL_23-KA-9101_EPR:VALUE': 'PH (CBM) 1st Stage ExpPress Ratio',
 'VAL_23-KA-9101_ESP:VALUE': 'PH (CBM) 1st Stage ExpShaft Power',
 'VAL_23-KA-9101_PED:VALUE': 'PH (CBM) 1st Stage Poly Eff Dev',
 'VAL_23-KA-9101_PHD:VALUE': 'PH (CBM) 1st Stage Poly Head Dev',
 'VAL_23-KA-9101_PRD:VALUE': 'PH (CBM) 1st Stage Press Rat Dev',
 'VAL_23-KA-9101_SPD:VALUE': 'PH (CBM) 1st Stage Shft Pwr Dev'}
MultiIndex([('VAL_23-KA-9101_EPR:VALUE', 'average'),
            ('VAL_23-KA-9101_PHD:VALUE', 'average'),
            ('VAL_23-KA-9101_ASP:VALUE', 'average'),
            ('VAL_23-KA-9101_PRD:VALUE', 'average'),
            ('VAL_23-KA-9101_APH:VALUE', 'average'),
            ('VAL_23-KA-9101_PED:VALUE', 'average'),
            ('VAL_23-KA-9101_SPD:VALUE', 'average'),
            ('VAL_23-KA-9101_APE:VALUE', 'average'),
            ('VAL_23-KA-9101_EPE:VALUE', 'average'),
            ('VAL_23-KA-9101_ESP:VALUE', 'average'),
            ('VAL_23-KA-9101_APR:VALUE', 'average'),
            ('VAL_23-KA-9101_EPH:VALUE', 'average')],
           names=['identifier', 'aggregate'])

In [10]:
df.tail()

identifier,PH (CBM) 1st Stage ExpPress Ratio,PH (CBM) 1st Stage Poly Head Dev,PH (CBM) 1st Stage ActShaft Power,PH (CBM) 1st Stage Press Rat Dev,PH (CBM) 1st Stg ActCompr Poly Head,PH (CBM) 1st Stage Poly Eff Dev,PH (CBM) 1st Stage Shft Pwr Dev,PH (CBM) 1st Stage ActCompr Poly Eff,PH (CBM) 1st Stage ExpCompr Poly Eff,PH (CBM) 1st Stage ExpShaft Power,PH (CBM) 1st Stage ActPress Ratio,PH (CBM) 1st Stg ExpCompr Poly Head
aggregate,average,average,average,average,average,average,average,average,average,average,average,average
2020-03-01 02:57:52,2.873428,21.737337,9581.932694,24.953387,164.122373,NaN,15.311577,83.655328,79.238867,8308.720221,3.590546,134.812568
2020-03-01 02:58:22,2.789148,23.996879,10360.703495,27.131556,161.901347,NaN,16.464863,83.108256,78.076905,8898.043657,3.543732,130.649197
2020-03-01 02:58:52,3.102035,9.302431,9850.780832,12.095792,159.143382,NaN,7.550235,82.012710,80.696562,9160.199229,3.476781,145.619097
2020-03-01 02:59:22,3.232144,5.882710,9144.089359,8.651207,160.400352,NaN,3.414796,82.739214,80.808337,8842.232082,3.511954,151.481747
2020-03-01 02:59:52,3.198250,8.702010,8952.813424,11.936310,163.042787,NaN,4.765859,83.868926,80.828725,8545.773223,3.580271,149.980894

In [11]:
info.head()

,id,created_time,last_updated_time,is_step,is_string,external_id,name,metadata,asset_id,description,security_categories,unit
0,460210694425061,2020-06-24 18:51:54.298,2026-03-23 13:05:25.440,False,False,VAL_23-KA-9101_EPR:VALUE,VAL_23-KA-9101_EPR:VALUE,"{'compdev': '0', 'location5': '2', 'pointtype'...",3047932288982463,PH (CBM) 1st Stage ExpPress Ratio,[],NaN
1,1669469338541465,2020-06-24 18:51:54.298,2026-03-23 13:05:26.777,False,False,VAL_23-KA-9101_PHD:VALUE,VAL_23-KA-9101_PHD:VALUE,"{'compdev': '0', 'location5': '2', 'pointtype'...",3047932288982463,PH (CBM) 1st Stage Poly Head Dev,[],NaN
2,3386754896121434,2020-06-24 18:51:54.298,2026-03-23 13:05:23.392,False,False,VAL_23-KA-9101_ASP:VALUE,VAL_23-KA-9101_ASP:VALUE,"{'compdev': '0', 'location5': '2', 'pointtype'...",3047932288982463,PH (CBM) 1st Stage ActShaft Power,[],kw
3,3702305190557142,2020-06-24 18:51:54.298,2026-03-23 13:05:27.363,False,False,VAL_23-KA-9101_PRD:VALUE,VAL_23-KA-9101_PRD:VALUE,"{'compdev': '0', 'location5': '2', 'pointtype'...",3047932288982463,PH (CBM) 1st Stage Press Rat Dev,[],%
4,4012168589282214,2020-06-24 18:51:54.298,2026-03-23 13:05:22.326,False,False,VAL_23-KA-9101_APH:VALUE,VAL_23-KA-9101_APH:VALUE,"{'compdev': '0', 'location5': '2', 'pointtype'...",3047932288982463,PH (CBM) 1st Stg ActCompr Poly Head,[],NaN

In [12]:
df.shape

(547508, 12)

In [13]:
df.to_csv("compressor.csv")